"""The official BIP-322 test vectors (bip-0322/*.json, generated by the btcd reference)."""

import pytest

from bip322core.verify import State, verify_message
from tests.conftest import load_vectors

BASIC = load_vectors("basic-test-vectors.json")
GENERATED = load_vectors("generated-test-vectors.json")


def _valid_cases():
    cases = []
    for v in BASIC["simple"]:
        for s in v["bip322_signatures"]:
            cases.append(pytest.param(v["message"], v["address"], s, id=f"basic-{v['type']}"))
    for section in ("simple", "full", "proof_of_funds"):
        for v in GENERATED[section]:
            for s in v["bip322_signatures"]:
                cases.append(pytest.param(v["message"], v["address"], s, id=f"{section}-{v['type']}"))
    return cases


def _error_cases():
    cases = []
    for v in BASIC["error"]:
        cases.append(pytest.param(v["message"], v["address"], v["signature"], id="basic-" + v["description"][:40]))
    for v in GENERATED["error"]:
        cases.append(pytest.param(v["message"], v["address"], v["signature"], id="gen-" + v["description"][:50]))
    return cases


@pytest.mark.parametrize("message,address,signature", _valid_cases())
def test_valid_vectors(message, address, signature, kernel_engines):
    result = verify_message(address, signature, message.encode("utf-8"), engines=kernel_engines)
    assert result.state is State.VALID, result.reason
    assert all(run.ok for run in result.engines)


@pytest.mark.parametrize("message,address,signature", _error_cases())
def test_error_vectors(message, address, signature, kernel_engines):
    result = verify_message(address, signature, message.encode("utf-8"), engines=kernel_engines)
    assert result.state is State.INVALID, result.reason


def test_time_locked_vectors_report_locktime():
    for v in GENERATED["full"]:
        if "time-lock" not in v["type"]:
            continue
        result = verify_message(v["address"], v["bip322_signatures"][0], v["message"].encode())
        assert result.ok
        assert result.locktime == int(v["lock_time"])
        assert result.sequence == int(v["sequence"])
        assert result.version == int(v["tx_version"])
